name: BMI Calculator

on:
  push:
    branches:
      - main

jobs:
  calculating:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run cypress test
        run: npm run test:e2e

      - name: Run Cypress in Headless Mode
        run: cypress run --headless
